### ISSUE TITLE
For Bufferig processing class name of the smooth streaming

### ISSUE THREAD

**Issue by grapevine23** [sonyxperiadev/MultimediaForAndroidLibrary#10]
For smooth streaming.

In this library, although using the DASHBufferedDataSource in Buffering processing of smooth streaming, those who changed the name of the class is good.
MPEG-DASH and smooth streaming in and to use the same class is no problem. BufferedDataSource and, it is better that was changed to CommonBufferedDataSource like.

Best regards.

**Comment by ghost** [comment]
Hi.

Thanks for your comment. That is a good suggestion. Let us investigate.

**Comment by grapevine23** [comment]
Thank you answer. This question will be closed.
