### ISSUE TITLE
Why the minimum sdk verson is 19?

### ISSUE THREAD

**Issue by IlyaMyasoedov** [sonyxperiadev/MultimediaForAndroidLibrary#13]
Hello. Your project is great, thanks for your work but i can't use it in my project because of the high minimum sdk version of MultimediaForAndroidLibrary.

**Comment by ghost** [comment]
Hi.

The reason for 19 as API level is due to that some functions in MediaCodec API requires API Level 19.
http://developer.android.com/reference/android/media/MediaCodec.html

/Jimmy

**Comment by IlyaMyasoedov** [comment]
Thanks for your reply. Good luck!!
