### ISSUE TITLE
Unsupported smooth streaming

### ISSUE THREAD

**Issue by kienbk1910** [sonyxperiadev/MultimediaForAndroidLibrary#2]
I find smooth streaming option in demo app, But I think library unsupported

**Comment by JimmyDahlqvist** [comment]
Hi and thank you for your comment.

You are correct, the library do not support Smooth Streaming.
The wording in the demo application is incorrect.

Regards
Jimmy

**Comment by kienbk1910** [comment]
Thank for your support, I want to implement smooth streaming . Do you have advice ?

**Comment by JimmyDahlqvist** [comment]
Smooth streaming is similar to DASH.
Have a look at the DASH implementation and try and do a Smooth Streaming implementation in the same way.

Upload you changes as a pull request, if you upload in increments we might be able to guide you.
