### ISSUE TITLE
I think the set value of the Read Timeout is short

### ISSUE THREAD

**Issue by grapevine23** [sonyxperiadev/MultimediaForAndroidLibrary#7]
There is a request for openHttpConnection of HttpURLConnection.

In httpConnection.setReadTimeout (5000), but have set the ReadTimeout to 5 seconds, I think it short.
Given the use of the move, who a little more long is good.

Since the Timeout of the conventional model has been set at around 15 seconds, I want you to fix in 15 seconds.

Best regards

**Comment by JimmyDahlqvist** [comment]
We have not seen any problem with a short read timeout. We wanted to keep it as short as possible. What device / network are you using that are causing the problem?

You are welcome to contribute the change via a pull request.

/Jimmy

**Comment by grapevine23** [comment]
Thank you answer.
That's the idea that there is no problem in 5 seconds. It was found.
